package com.ishidai.core.utils;

import java.util.Date;
import java.util.Properties;

import org.mybatis.generator.api.CommentGenerator;
import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.CompilationUnit;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.InnerClass;
import org.mybatis.generator.api.dom.java.InnerEnum;
import org.mybatis.generator.api.dom.java.JavaElement;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;
import org.mybatis.generator.internal.util.StringUtility;

public class MyCommentGenetatro implements CommentGenerator {
    private Properties properties = new Properties();
    private boolean suppressDate = false;
    private boolean suppressAllComments = false;

    public void addJavaFileComment(CompilationUnit paramCompilationUnit) {
    }

    public void addComment(XmlElement paramXmlElement) {
        if (this.suppressAllComments)
            return;
        paramXmlElement.addElement(new TextElement("<!--"));
        StringBuilder localStringBuilder = new StringBuilder();
        localStringBuilder.append("  WARNING - ");
        localStringBuilder.append("@mbggenerated");
        paramXmlElement.addElement(new TextElement(localStringBuilder.toString()));
        paramXmlElement.addElement(new TextElement(
                "  This element is automatically generated by MyBatis Generator, do not modify."));
        String str = getDateString();
        if (str != null) {
            localStringBuilder.setLength(0);
            localStringBuilder.append("  This element was generated on ");
            localStringBuilder.append(str);
            localStringBuilder.append('.');
            paramXmlElement.addElement(new TextElement(localStringBuilder.toString()));
        }
        paramXmlElement.addElement(new TextElement("-->"));
    }

    public void addRootComment(XmlElement paramXmlElement) {
    }

    public void addConfigurationProperties(Properties paramProperties) {
        this.properties.putAll(paramProperties);
        this.suppressDate = StringUtility.isTrue(paramProperties.getProperty("suppressDate"));
        this.suppressAllComments = StringUtility.isTrue(paramProperties.getProperty("suppressAllComments"));
    }

    protected void addJavadocTag(JavaElement paramJavaElement, boolean paramBoolean) {
        // paramJavaElement.addJavaDocLine(" *");
        // StringBuilder localStringBuilder = new StringBuilder();
        // localStringBuilder.append(" * ");
        // localStringBuilder.append("@mbggenerated");
        // if (paramBoolean)
        // localStringBuilder.append(" do_not_delete_during_merge");
        // String str = getDateString();
        // if (str != null)
        // {
        // localStringBuilder.append(' ');
        // localStringBuilder.append(str);
        // }
        // paramJavaElement.addJavaDocLine(localStringBuilder.toString());
    }

    protected String getDateString() {
        if (this.suppressDate)
            return null;
        return new Date().toString();
    }

    public void addClassComment(InnerClass paramInnerClass, IntrospectedTable paramIntrospectedTable) {
        // if (this.suppressAllComments)
        // return;
        // StringBuilder localStringBuilder = new StringBuilder();
        // paramInnerClass.addJavaDocLine("/**");
        // paramInnerClass.addJavaDocLine(" * This class was generated by MyBatis Generator.");
        // localStringBuilder.append(" * This class corresponds to the database table ");
        // localStringBuilder.append(paramIntrospectedTable.getFullyQualifiedTable());
        // paramInnerClass.addJavaDocLine(localStringBuilder.toString());
        // addJavadocTag(paramInnerClass, false);
        // paramInnerClass.addJavaDocLine(" */");
    }

    public void addEnumComment(InnerEnum paramInnerEnum, IntrospectedTable paramIntrospectedTable) {
        // if (this.suppressAllComments)
        // return;
        // StringBuilder localStringBuilder = new StringBuilder();
        // paramInnerEnum.addJavaDocLine("/**");
        // paramInnerEnum.addJavaDocLine(" * This enum was generated by MyBatis Generator.");
        // localStringBuilder.append(" * This enum corresponds to the database table ");
        // localStringBuilder.append(paramIntrospectedTable.getFullyQualifiedTable());
        // paramInnerEnum.addJavaDocLine(localStringBuilder.toString());
        // addJavadocTag(paramInnerEnum, false);
        // paramInnerEnum.addJavaDocLine(" */");
    }

    public void addFieldComment(Field paramField, IntrospectedTable paramIntrospectedTable,
            IntrospectedColumn paramIntrospectedColumn) {
        if (paramIntrospectedColumn.getRemarks() != null && !paramIntrospectedColumn.getRemarks().equals("")) {
            paramField.addJavaDocLine("/**");
            paramField.addJavaDocLine(" * " + paramIntrospectedColumn.getRemarks());
            addJavadocTag(paramField, false);
            paramField.addJavaDocLine(" */");
        }
    }

    public void addFieldComment(Field paramField, IntrospectedTable paramIntrospectedTable) {
        // if (this.suppressAllComments)
        // return;
        // StringBuilder localStringBuilder = new StringBuilder();
        // paramField.addJavaDocLine("/**");
        // paramField.addJavaDocLine(" * This field was generated by MyBatis Generator.");
        // localStringBuilder.append(" * This field corresponds to the database table ");
        // localStringBuilder.append(paramIntrospectedTable.getFullyQualifiedTable());
        // paramField.addJavaDocLine(localStringBuilder.toString());
        // addJavadocTag(paramField, false);
        // paramField.addJavaDocLine(" */");
    }

    public void addGeneralMethodComment(Method paramMethod, IntrospectedTable paramIntrospectedTable) {
        // if (this.suppressAllComments)
        // return;
        // StringBuilder localStringBuilder = new StringBuilder();
        // paramMethod.addJavaDocLine("/**");
        // paramMethod.addJavaDocLine(" * This method was generated by MyBatis Generator.");
        // localStringBuilder.append(" * This method corresponds to the database table ");
        // localStringBuilder.append(paramIntrospectedTable.getFullyQualifiedTable());
        // paramMethod.addJavaDocLine(localStringBuilder.toString());
        // addJavadocTag(paramMethod, false);
        // paramMethod.addJavaDocLine(" */");
    }

    public void addGetterComment(Method paramMethod, IntrospectedTable paramIntrospectedTable,
            IntrospectedColumn paramIntrospectedColumn) {
        // if (this.suppressAllComments)
        // return;
        // StringBuilder localStringBuilder = new StringBuilder();
        // paramMethod.addJavaDocLine("/**");
        // paramMethod.addJavaDocLine(" * This method was generated by MyBatis Generator.");
        // localStringBuilder.append(" * This method returns the value of the database column ");
        // localStringBuilder.append(paramIntrospectedTable.getFullyQualifiedTable());
        // localStringBuilder.append('.');
        // localStringBuilder.append(paramIntrospectedColumn.getActualColumnName());
        // paramMethod.addJavaDocLine(localStringBuilder.toString());
        // paramMethod.addJavaDocLine(" *");
        // localStringBuilder.setLength(0);
        // localStringBuilder.append(" * @return the value of ");
        // localStringBuilder.append(paramIntrospectedTable.getFullyQualifiedTable());
        // localStringBuilder.append('.');
        // localStringBuilder.append(paramIntrospectedColumn.getActualColumnName());
        // paramMethod.addJavaDocLine(localStringBuilder.toString());
        // addJavadocTag(paramMethod, false);
        // paramMethod.addJavaDocLine(" */");
    }

    public void addSetterComment(Method paramMethod, IntrospectedTable paramIntrospectedTable,
            IntrospectedColumn paramIntrospectedColumn) {
        // if (this.suppressAllComments)
        // return;
        // StringBuilder localStringBuilder = new StringBuilder();
        // paramMethod.addJavaDocLine("/**");
        // paramMethod.addJavaDocLine(" * This method was generated by MyBatis Generator.");
        // localStringBuilder.append(" * This method sets the value of the database column ");
        // localStringBuilder.append(paramIntrospectedTable.getFullyQualifiedTable());
        // localStringBuilder.append('.');
        // localStringBuilder.append(paramIntrospectedColumn.getActualColumnName());
        // paramMethod.addJavaDocLine(localStringBuilder.toString());
        // paramMethod.addJavaDocLine(" *");
        // Parameter localParameter =
        // (Parameter)paramMethod.getParameters().get(0);
        // localStringBuilder.setLength(0);
        // localStringBuilder.append(" * @param ");
        // localStringBuilder.append(localParameter.getName());
        // localStringBuilder.append(" the value for ");
        // localStringBuilder.append(paramIntrospectedTable.getFullyQualifiedTable());
        // localStringBuilder.append('.');
        // localStringBuilder.append(paramIntrospectedColumn.getActualColumnName());
        // paramMethod.addJavaDocLine(localStringBuilder.toString());
        // addJavadocTag(paramMethod, false);
        // paramMethod.addJavaDocLine(" */");
    }

    public void addClassComment(InnerClass paramInnerClass, IntrospectedTable paramIntrospectedTable,
            boolean paramBoolean) {
        // if (this.suppressAllComments)
        // return;
        // StringBuilder localStringBuilder = new StringBuilder();
        // paramInnerClass.addJavaDocLine("/**");
        // paramInnerClass.addJavaDocLine(" * This class was generated by MyBatis Generator.");
        // localStringBuilder.append(" * This class corresponds to the database table ");
        // localStringBuilder.append(paramIntrospectedTable.getFullyQualifiedTable());
        // paramInnerClass.addJavaDocLine(localStringBuilder.toString());
        // addJavadocTag(paramInnerClass, paramBoolean);
        // paramInnerClass.addJavaDocLine(" */");
    }
}
